"use strict";
module.exports={
    INITIALIZE:"INITIALIZE",
    CREATE_AUTHOR: "CREATE_AUTHOR",
    UPDATE_AUTHOR: "UPDATE_AUTHOR",
    DELETE_AUTHOR:"DELETE_AUTHOR",
    CREATE_COURSE: "CREATE_COURSE",
    UPDATE_COURSE: "UPDATE_COURSE",
    DELETE_COURSE:"DELETE_COURSE"
}